apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: mock-consumer-service
spec:
  selector:
    app: mock-consumer-service
  ports:
    - protocol: "TCP"
      port: 8003 # The port that the service is running on in the cluster
      targetPort: 8003 # The port exposed by the service
  type: Mock # type of the service.
---
apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: mock-consumer-service
spec:
  selector:
    matchLabels:
      app: mock-consumer-service
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: mock-consumer-service
    spec:
      containers:
        - name: mock-consumer-service
          image: dinnerinmotion/mock-consumer-service # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003 # The port that the container is running on in the cluster
